backward_config:
  enable_backward_config: 0
  freeze_fc: 0
  manual_weight_idx: 21-24-27-30-36-39
  n_bias_update: 22
  n_weight_update: null
  pw1_weight_only: 0
  quantize_gradient: 0
  train_scale: 0
  weight_select_criteria: magnitude+
  weight_update_ratio: 1-1-1-1-0.125-0.25
data_provider:
  base_batch_size: 64
  color_aug: 0.4
  dataset: image_folder
  image_size: 112
  lfw_root: data/
  n_worker: 8
  num_classes: 100
  resize_scale: 0.08
  root: data/human
evaluate: false
loss_config:
  embedding_size: 128
  margin: 0.5
  s: 1.0
manual_seed: 0
net_config:
  cls_head: linear
  dropout: 0.0
  mcu_head_type: fp
  net_name: mcunet-5fps
  pretrained: false
ray_tune: 0
resume: 0
run_config:
  base_lr: 0.01
  bias_only: 0
  bs256_lr: 0.1
  eval_per_epochs: 50
  fc_lr10: 0
  fc_only: 0
  grid_ckpt_path: null
  grid_output: null
  lr_schedule_name: cosine
  n_block_update: -1
  n_epochs: 50
  no_wd_keys:
  - norm
  - bias
  optimizer_name: sgd_nomom
  warmup_epochs: 0
  warmup_lr: 0
  weight_decay: 0
run_dir: runs/human/mcunet-5fps/sparse_100kb/sgd_qas_nomom
